import type { DatabaseType } from "@/lib/types";
import { quoteIdentifier } from "@/lib/sql/identifier";

// Adapted from upstream 2f78fc76. This module only builds preview SQL; it never executes it.
export interface ColumnDefinition {
  name: string;
  type: string;
  isPrimary: boolean;
  isNullable: boolean;
  isUnique: boolean;
  defaultValue: string;
}

export const AUTO_INCREMENT = "__auto_increment__";

interface CreateTableDialect {
  autoIncrement: string | null;
  autoIncrementSequence?: true;
  supportsConstraints: boolean;
  keyType: string;
  types: readonly string[];
}

const SQLITE_DIALECT: CreateTableDialect = {
  autoIncrement: "INTEGER PRIMARY KEY AUTOINCREMENT",
  supportsConstraints: true,
  keyType: "INTEGER",
  types: ["TEXT", "INTEGER", "REAL", "BLOB", "NUMERIC"],
};
const POSTGRES_DIALECT: CreateTableDialect = {
  autoIncrement: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  supportsConstraints: true,
  keyType: "INTEGER",
  types: [
    "VARCHAR(255)",
    "TEXT",
    "INTEGER",
    "BIGINT",
    "BOOLEAN",
    "TIMESTAMP",
    "DATE",
    "JSONB",
    "UUID",
    "DECIMAL(10,2)",
  ],
};

// Same eight supported form dialects as upstream. Provider capabilities gate access.
const DIALECTS: Partial<Record<DatabaseType, CreateTableDialect>> = {
  postgres: POSTGRES_DIALECT,
  mysql: {
    autoIncrement: "INT AUTO_INCREMENT PRIMARY KEY",
    supportsConstraints: true,
    keyType: "INT",
    types: [
      "VARCHAR(255)",
      "TEXT",
      "INT",
      "BIGINT",
      "BOOLEAN",
      "TIMESTAMP",
      "DATE",
      "JSON",
      "CHAR(36)",
      "DECIMAL(10,2)",
    ],
  },
  sqlite: SQLITE_DIALECT,
  libsql: SQLITE_DIALECT,
  mssql: {
    autoIncrement: "INT IDENTITY(1,1) PRIMARY KEY",
    supportsConstraints: true,
    keyType: "INT",
    types: [
      "VARCHAR(255)",
      "NVARCHAR(MAX)",
      "INT",
      "BIGINT",
      "BIT",
      "DATETIME2",
      "DATE",
      "UNIQUEIDENTIFIER",
      "DECIMAL(10,2)",
    ],
  },
  oracle: {
    autoIncrement: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    supportsConstraints: true,
    keyType: "INTEGER",
    types: [
      "VARCHAR2(255)",
      "CLOB",
      "INTEGER",
      "NUMBER(19)",
      "NUMBER(1)",
      "TIMESTAMP",
      "DATE",
      "RAW(16)",
      "NUMBER(10,2)",
    ],
  },
  duckdb: {
    autoIncrement: "INTEGER PRIMARY KEY",
    autoIncrementSequence: true,
    supportsConstraints: true,
    keyType: "INTEGER",
    types: [
      "VARCHAR(255)",
      "TEXT",
      "INTEGER",
      "BIGINT",
      "BOOLEAN",
      "TIMESTAMP",
      "DATE",
      "JSON",
      "UUID",
      "DECIMAL(10,2)",
    ],
  },
  trino: {
    autoIncrement: null,
    supportsConstraints: false,
    keyType: "INTEGER",
    types: [
      "VARCHAR(255)",
      "VARCHAR",
      "INTEGER",
      "BIGINT",
      "BOOLEAN",
      "TIMESTAMP",
      "DATE",
      "JSON",
      "UUID",
      "DECIMAL(10,2)",
    ],
  },
};

export function resolveCreateTableDialect(dbType?: DatabaseType): CreateTableDialect {
  return (dbType && DIALECTS[dbType]) || POSTGRES_DIALECT;
}

export function defaultColumns(dbType?: DatabaseType): ColumnDefinition[] {
  const dialect = resolveCreateTableDialect(dbType);
  return [
    {
      name: "id",
      type: dialect.autoIncrement ? AUTO_INCREMENT : dialect.keyType,
      isPrimary: dialect.supportsConstraints,
      isNullable: false,
      isUnique: dialect.supportsConstraints,
      defaultValue: "",
    },
  ];
}

// Unlike upstream's full reset, retain compatible user intent. Only literal
// defaults are portable; dialect-specific expressions must be entered again.
export function reconcileColumns(columns: ColumnDefinition[], dbType?: DatabaseType): ColumnDefinition[] {
  const dialect = resolveCreateTableDialect(dbType);
  return columns.map((col) => {
    const isPrimary = col.isPrimary && dialect.supportsConstraints;
    let type = col.type;
    if (type === AUTO_INCREMENT) {
      if (!isPrimary || !dialect.autoIncrement) type = dialect.keyType;
    } else if (!dialect.types.includes(type)) {
      type = type === "INT" || type === "INTEGER" ? dialect.keyType : dialect.types[0];
    }
    const defaultValue = /^(?:NULL|[+-]?\d+(?:\.\d+)?|'(?:[^']|'')*')$/i.test(col.defaultValue.trim())
      ? col.defaultValue
      : "";
    return { ...col, type, isPrimary, isUnique: col.isUnique && dialect.supportsConstraints, defaultValue };
  });
}

export function generateCreateTableSQL(tableName: string, columns: ColumnDefinition[], dbType?: DatabaseType): string {
  if (!tableName.trim()) return "";
  const dialect = resolveCreateTableDialect(dbType);
  const quote = (name: string) => quoteIdentifier(name, dbType);
  const prelude: string[] = [];
  const colDefs = columns.map((col) => {
    if (col.type === AUTO_INCREMENT && col.isPrimary && dialect.autoIncrement) {
      let clause = `${quote(col.name)} ${dialect.autoIncrement}`;
      if (dialect.autoIncrementSequence) {
        const sequence = quote(`${tableName}_${col.name}_seq`);
        prelude.push(`CREATE SEQUENCE IF NOT EXISTS ${sequence};`);
        clause += ` DEFAULT nextval('${sequence.replace(/'/g, "''")}')`;
      }
      return `  ${clause}`;
    }
    const type = col.type === AUTO_INCREMENT ? dialect.keyType : col.type;
    const isPrimary = col.isPrimary && dialect.supportsConstraints;
    let constraints = isPrimary ? " PRIMARY KEY" : "";
    if (!col.isNullable && !isPrimary) constraints += " NOT NULL";
    if (col.isUnique && !isPrimary && dialect.supportsConstraints) constraints += " UNIQUE";
    // Types come from the form's fixed list. Defaults remain SQL expressions, not
    // string literals to translate/escape. The existing form has no default input.
    const defaultValue = col.defaultValue ? ` DEFAULT ${col.defaultValue}` : "";
    const modifiers = dbType === "oracle" ? `${defaultValue}${constraints}` : `${constraints}${defaultValue}`;
    return `  ${quote(col.name)} ${type}${modifiers}`;
  });
  const create = `CREATE TABLE ${quote(tableName)} (\n${colDefs.join(",\n")}\n);`;
  return prelude.length ? `${prelude.join("\n")}\n${create}` : create;
}
