-- Applied only by seed.ts after its target/schema guards, inside one transaction.
CREATE SCHEMA apple_store_lab;
SET LOCAL search_path = apple_store_lab, pg_catalog;

CREATE TABLE categorias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL UNIQUE
);
CREATE TABLE produtos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  sku TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  preco NUMERIC(12,2) NOT NULL CHECK (preco >= 0),
  custo NUMERIC(12,2) NOT NULL CHECK (custo >= 0),
  ativo BOOLEAN NOT NULL
);
CREATE TABLE fornecedores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  identificador_ficticio TEXT NOT NULL UNIQUE CHECK (identificador_ficticio LIKE 'FORNECEDOR-LAB-%'),
  email TEXT NOT NULL UNIQUE CHECK (email LIKE '%@example.test')
);
CREATE TABLE clientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf_ficticio VARCHAR(14) NOT NULL UNIQUE CHECK (cpf_ficticio ~ '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}$'),
  data_nascimento DATE NOT NULL,
  email TEXT NOT NULL UNIQUE CHECK (email LIKE '%@example.test'),
  telefone TEXT NOT NULL CHECK (telefone LIKE 'TEL-LAB-%'),
  endereco TEXT NOT NULL,
  numero TEXT NOT NULL,
  complemento TEXT,
  bairro TEXT NOT NULL,
  cidade TEXT NOT NULL,
  estado CHAR(2) NOT NULL CHECK (estado ~ '^[A-Z]{2}$'),
  cep_ficticio TEXT NOT NULL CHECK (cep_ficticio LIKE 'CEP-LAB-%'),
  data_cadastro TIMESTAMPTZ NOT NULL,
  ativo BOOLEAN NOT NULL
);
CREATE TABLE funcionarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cargo TEXT NOT NULL CHECK (cargo IN ('vendedor','supervisor','caixa','gerente','estoque')),
  email TEXT NOT NULL UNIQUE CHECK (email LIKE '%@example.test'),
  ativo BOOLEAN NOT NULL
);
CREATE TABLE vendas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INTEGER NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  funcionario_id INTEGER NOT NULL REFERENCES funcionarios(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  data_venda TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('CONCLUIDA','PENDENTE','CANCELADA')),
  forma_pagamento TEXT NOT NULL CHECK (forma_pagamento IN ('PIX','CREDITO','DEBITO','DINHEIRO','BOLETO')),
  canal TEXT NOT NULL CHECK (canal IN ('LOJA','ONLINE','RETIRADA')),
  desconto NUMERIC(12,2) NOT NULL CHECK (desconto >= 0),
  valor_total NUMERIC(12,2) NOT NULL CHECK (valor_total >= 0)
);
CREATE TABLE itens_venda (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id INTEGER NOT NULL REFERENCES vendas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  produto_id INTEGER NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  quantidade INTEGER NOT NULL CHECK (quantidade > 0),
  preco_unitario NUMERIC(12,2) NOT NULL CHECK (preco_unitario >= 0),
  desconto_item NUMERIC(12,2) NOT NULL CHECK (desconto_item >= 0),
  subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0 AND subtotal = preco_unitario * quantidade - desconto_item),
  UNIQUE (venda_id, produto_id)
);
CREATE TABLE entradas_estoque (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fornecedor_id INTEGER NOT NULL REFERENCES fornecedores(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  produto_id INTEGER NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  quantidade INTEGER NOT NULL CHECK (quantidade > 0),
  custo_unitario NUMERIC(12,2) NOT NULL CHECK (custo_unitario >= 0),
  data_entrada TIMESTAMPTZ NOT NULL,
  nota_fiscal_ficticia TEXT NOT NULL UNIQUE CHECK (nota_fiscal_ficticia LIKE 'NF-FICTICIA-LAB-%')
);
CREATE TABLE movimentacoes_estoque (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id INTEGER NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  tipo TEXT NOT NULL CHECK (tipo IN ('ENTRADA','SAIDA','AJUSTE')),
  quantidade INTEGER NOT NULL CHECK (quantidade <> 0),
  data_movimentacao TIMESTAMPTZ NOT NULL,
  entrada_id INTEGER UNIQUE REFERENCES entradas_estoque(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  item_venda_id INTEGER UNIQUE REFERENCES itens_venda(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  motivo TEXT NOT NULL,
  CHECK (
    (tipo = 'ENTRADA' AND quantidade > 0 AND entrada_id IS NOT NULL AND item_venda_id IS NULL) OR
    (tipo = 'SAIDA' AND quantidade < 0 AND entrada_id IS NULL AND item_venda_id IS NOT NULL) OR
    (tipo = 'AJUSTE' AND entrada_id IS NULL AND item_venda_id IS NULL)
  )
);
CREATE TABLE estoque (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id INTEGER NOT NULL UNIQUE REFERENCES produtos(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  quantidade INTEGER NOT NULL CHECK (quantidade >= 0),
  estoque_minimo INTEGER NOT NULL CHECK (estoque_minimo >= 0),
  localizacao TEXT NOT NULL,
  ultima_atualizacao TIMESTAMPTZ NOT NULL
);
CREATE TABLE metadata_teste (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id = 1),
  fixture_id TEXT NOT NULL UNIQUE,
  versao TEXT NOT NULL,
  seed BIGINT NOT NULL,
  clientes_previstos INTEGER NOT NULL,
  data_logica DATE NOT NULL,
  descricao TEXT NOT NULL,
  aviso_cpf TEXT NOT NULL,
  aviso_comercial TEXT NOT NULL
);

CREATE INDEX ON produtos (categoria_id);
CREATE INDEX ON produtos (nome);
CREATE INDEX ON estoque (quantidade);
CREATE INDEX ON clientes (nome);
CREATE INDEX ON clientes (cidade, estado);
CREATE INDEX ON clientes (data_nascimento);
CREATE INDEX ON vendas (cliente_id);
CREATE INDEX ON vendas (funcionario_id);
CREATE INDEX ON vendas (data_venda);
CREATE INDEX ON vendas (status);
-- UNIQUE(venda_id, produto_id) already covers venda_id lookups.
CREATE INDEX ON itens_venda (produto_id);
CREATE INDEX ON entradas_estoque (fornecedor_id);
CREATE INDEX ON entradas_estoque (produto_id);
CREATE INDEX ON movimentacoes_estoque (produto_id, data_movimentacao);

CREATE VIEW produtos_com_estoque AS
SELECT p.id, p.nome, c.nome AS categoria, p.preco, p.ativo, e.quantidade, e.estoque_minimo,
  CASE WHEN e.quantidade = 0 THEN 'SEM ESTOQUE'
       WHEN e.quantidade < e.estoque_minimo THEN 'ESTOQUE BAIXO' ELSE 'OK' END AS status_estoque
FROM produtos p JOIN categorias c ON c.id = p.categoria_id JOIN estoque e ON e.produto_id = p.id;

CREATE VIEW resumo_vendas AS
SELECT v.id AS venda_id, v.data_venda, c.nome AS cliente, c.cidade, c.estado,
  f.nome AS funcionario, v.canal, v.forma_pagamento, v.status, v.valor_total,
  COUNT(i.id) AS itens_distintos, COALESCE(SUM(i.quantidade), 0) AS unidades
FROM vendas v JOIN clientes c ON c.id = v.cliente_id JOIN funcionarios f ON f.id = v.funcionario_id
LEFT JOIN itens_venda i ON i.venda_id = v.id
GROUP BY v.id, c.id, f.id;
