import { createHash } from "node:crypto";
import { describe, expect, test } from "bun:test";
import { corpus } from "./corpus";
import { aggregate, DIALECTS, type StatementExpectation } from "./model";
import evidence from "./evaluation-results.json";

function walk(items: StatementExpectation[]): StatementExpectation[] {
  return items.flatMap((item) => [item, ...walk(item.children ?? [])]);
}
const get = (id: string) => {
  const item = corpus.find((entry) => entry.id === id);
  if (!item) throw new Error(`Missing corpus case: ${id}`);
  return item;
};

describe("6B.1 corpus oracle integrity (NOT production classifier tests)", () => {
  test("unique IDs and exact evidence fingerprint", () => {
    expect(new Set(corpus.map((item) => item.id)).size).toBe(corpus.length);
    expect(evidence.corpusCount).toBe(corpus.length);
    expect(evidence.corpusSha256).toBe(createHash("sha256").update(JSON.stringify(corpus)).digest("hex"));
  });

  for (const item of corpus) {
    test(item.id, () => {
      expect(item.sql.trim().length).toBeGreaterThan(0);
      expect(item.purpose.trim().length).toBeGreaterThan(0);
      expect(item.expected.aggregateEffects).toEqual(aggregate(item.expected.statements));
      const statements = walk(item.expected.statements);
      for (const entry of statements) {
        expect(entry.scopeIsSafe).toBe("not-proven");
        if (entry.operation === "update" || entry.operation === "delete") expect(typeof entry.hasWhere).toBe("boolean");
        expect(entry).not.toHaveProperty("allow");
        expect(entry).not.toHaveProperty("block");
        expect(entry).not.toHaveProperty("role");
        expect(entry).not.toHaveProperty("environment");
      }
      if (item.expected.status === "classified") expect(statements.length).toBeGreaterThan(0);
      if (item.expected.status === "invalid" || item.expected.status === "unsupported")
        expect(item.expected.aggregateEffects).toEqual([]);
      if (item.context) expect(item.context.effectiveSql).toBe(item.sql);
      for (const candidate of evidence.evaluations) {
        const observed = candidate.observations.filter((entry) => entry.id === item.id);
        expect(observed).toHaveLength(1);
        if (observed[0].outcome !== "parsed") {
          expect(observed[0]).not.toHaveProperty("nodes");
          expect(observed[0]).not.toHaveProperty("comparison");
        }
      }
    });
  }

  for (const dialect of DIALECTS) {
    test(`${dialect}: mandatory DML and negative intent distinctions are explicit`, () => {
      for (const command of ["update", "delete"]) {
        expect(get(`${dialect}/${command}-where`).expected.statements[0].hasWhere).toBe(true);
        expect(get(`${dialect}/${command}-all`).expected.statements[0].hasWhere).toBe(false);
      }
      expect(get(`${dialect}/where-true`).expected.statements[0]).toMatchObject({
        hasWhere: true,
        scopeIsSafe: "not-proven",
      });
      expect(get(`${dialect}/mixed-batch`).expected.aggregateEffects).toContain("write");
      for (const id of ["string-delete", "string-drop", "comment-keyword", "identifier"]) {
        expect(get(`${dialect}/${id}`).expected.aggregateEffects).toEqual(["read"]);
      }
      expect(get(`${dialect}/function`).expected.aggregateEffects).toContain("unknown-effects");
      expect(get(`${dialect}/function`).expected.status).toBe("partial");
      expect(get(`${dialect}/unknown`).expected.status).toBe("unknown");
    });
  }

  test("CTEs and EXPLAIN retain internal operations without making estimate execute them", () => {
    for (const id of ["cte-delete", "cte-update", "cte-nested-with-write"])
      expect(get(`postgres/${id}`).expected.aggregateEffects).toContain("write");
    expect(get("postgres/explain-estimate-delete").expected.aggregateEffects).toEqual(["read"]);
    expect(get("postgres/explain-estimate-delete").expected.statements[0].children?.[0].operation).toBe("delete");
    expect(get("postgres/explain-analyze-delete").expected.aggregateEffects).toEqual(["read", "write"]);
  });

  test("actual product SQL contains the dialect identities and migration effects", () => {
    expect(get("postgres/generated-create-table").sql).toContain(
      "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    );
    expect(get("mysql/generated-create-table").sql).toContain("INT AUTO_INCREMENT PRIMARY KEY");
    expect(get("sqlite/generated-create-table").sql).toContain("INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(get("mysql/generated-migration-alter").sql).toContain("DROP FOREIGN KEY");
    expect(get("postgres/generated-migration-alter").sql).toContain("DROP CONSTRAINT");
    for (const dialect of DIALECTS) {
      const sql = get(`${dialect}/generated-migration-alter`).sql;
      expect(sql).toContain("DROP INDEX");
      expect(sql).toContain("ADD COLUMN");
      expect(sql).toContain("CREATE UNIQUE INDEX");
    }
    expect(get("sqlite/generated-migration-alter").sql).toContain("Cannot drop foreign key");
  });
});
