import "../setup-dom";
import { mockToastError } from "../helpers/mock-sonner";
import React from "react";
import { afterEach, describe, expect, mock, test } from "bun:test";
import { cleanup, fireEvent, within } from "@testing-library/react";
import { renderWithIntl as render } from "../helpers/render-with-intl";
import { CreateTableModal } from "@/components/CreateTableModal";
import type { DatabaseType } from "@/lib/types";
import { loadMessages, mergeMessages } from "@/i18n/load-messages";

afterEach(cleanup);
const props = () => ({ isOpen: true, onClose: mock(() => {}), onTableCreated: mock(() => {}) });
function nameTable(baseElement: HTMLElement, name = "widgets") {
  fireEvent.change(baseElement.querySelector("#tableName")!, { target: { value: name } });
}
function chooseType(baseElement: HTMLElement, index: number, type: string) {
  fireEvent.keyDown(baseElement.querySelectorAll('[role="combobox"]')[index], { key: "ArrowDown" });
  fireEvent.click(within(baseElement).getByRole("option", { name: type }));
}
const engineKeys: Array<[DatabaseType, string]> = [
  ["postgres", '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'],
  ["mysql", "`id` INT AUTO_INCREMENT PRIMARY KEY"],
  ["sqlite", '"id" INTEGER PRIMARY KEY AUTOINCREMENT'],
  ["libsql", '"id" INTEGER PRIMARY KEY AUTOINCREMENT'],
  ["mssql", "[id] INT IDENTITY(1,1) PRIMARY KEY"],
  ["oracle", '"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'],
  ["duckdb", '"id" INTEGER PRIMARY KEY DEFAULT nextval(\'"widgets_id_seq"\')'],
  ["trino", '"id" INTEGER NOT NULL'],
];

describe("Create Table engine and locale regressions", () => {
  for (const [dbType, expected] of engineKeys) {
    test(`${dbType}: initializes correctly when connection arrives after mount`, () => {
      const callbacks = props();
      const { baseElement, rerender } = render(<CreateTableModal {...callbacks} />);
      rerender(<CreateTableModal {...callbacks} dbType={dbType} />);
      nameTable(baseElement);
      expect(baseElement.querySelector("pre")?.textContent).toContain(expected);
      expect(baseElement.querySelector("pre")?.textContent).not.toMatch(/SERIAL|__auto_increment__/);
      expect(callbacks.onTableCreated).not.toHaveBeenCalled();
    });
  }
  for (const dbType of ["postgres", "mysql", "sqlite"] as const) {
    test(`${dbType}: identical SQL in en/pt-BR, submitted only after an explicit click`, () => {
      const previews: string[] = [];
      for (const locale of ["en", "pt-BR"] as const) {
        const callbacks = props();
        const { baseElement, getByText } = render(<CreateTableModal {...callbacks} dbType={dbType} />, locale);
        expect(getByText(locale === "en" ? "Create New Table" : "Criar tabela")).toBeTruthy();
        expect(getByText(locale === "en" ? "SQL Preview" : "Prévia SQL")).toBeTruthy();
        nameTable(baseElement, "user_table");
        const sql = baseElement.querySelector("pre")!.textContent!;
        expect(sql).toContain("user_table");
        expect(callbacks.onTableCreated).not.toHaveBeenCalled();
        fireEvent.click(getByText("CREATE TABLE"));
        expect(callbacks.onTableCreated).toHaveBeenCalledTimes(1);
        expect(callbacks.onTableCreated).toHaveBeenCalledWith(sql);
        previews.push(sql);
        cleanup();
      }
      expect(previews[0]).toBe(previews[1]);
    });
    test(`${dbType}: clearing PK removes generated key and keeps a listed type`, () => {
      const { baseElement } = render(<CreateTableModal {...props()} dbType={dbType} />);
      nameTable(baseElement);
      fireEvent.click(baseElement.querySelectorAll('[role="checkbox"]')[0]);
      expect(baseElement.querySelector("pre")?.textContent).not.toMatch(
        /PRIMARY KEY|IDENTITY|AUTOINCREMENT|AUTO_INCREMENT/,
      );
      expect(baseElement.querySelector('[role="combobox"]')?.textContent).toBe(dbType === "mysql" ? "INT" : "INTEGER");
    });
  }
  test("engine switch retains columns and compatible flags while replacing JSONB", () => {
    const callbacks = props();
    const { baseElement, rerender, getByText } = render(<CreateTableModal {...callbacks} dbType="postgres" />);
    nameTable(baseElement);
    fireEvent.click(getByText("Add Column"));
    fireEvent.change(baseElement.querySelectorAll('input[placeholder="column_name"]')[1], {
      target: { value: "payload" },
    });
    chooseType(baseElement, 1, "JSONB");
    fireEvent.click(baseElement.querySelectorAll('[role="checkbox"]')[5]);
    rerender(<CreateTableModal {...callbacks} dbType="sqlite" />);
    const sql = baseElement.querySelector("pre")!.textContent!;
    expect(sql).toContain('CREATE TABLE "widgets"');
    expect(sql).toContain('"payload" TEXT UNIQUE');
    expect(sql).not.toContain("JSONB");
    expect(sql).toContain('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(baseElement.querySelectorAll('input[placeholder="column_name"]').length).toBe(2);
    expect(callbacks.onTableCreated).not.toHaveBeenCalled();
  });
  test("compatible column edits survive an unnamed table's engine switch", () => {
    const callbacks = props();
    const { baseElement, rerender } = render(<CreateTableModal {...callbacks} dbType="postgres" />);
    chooseType(baseElement, 0, "TEXT");
    rerender(<CreateTableModal {...callbacks} dbType="sqlite" />);
    expect(baseElement.querySelector('[role="combobox"]')?.textContent).toBe("TEXT");
  });
  test("Trino reset does not freeze defaults for the next SQLite connection", () => {
    const callbacks = props();
    const { baseElement, rerender, getByText } = render(<CreateTableModal {...callbacks} dbType="trino" />);
    expect(baseElement.querySelectorAll('[role="checkbox"]').length).toBe(1);
    nameTable(baseElement);
    fireEvent.click(getByText("CREATE TABLE"));
    rerender(<CreateTableModal {...callbacks} dbType="sqlite" />);
    nameTable(baseElement);
    expect(baseElement.querySelector("pre")?.textContent).toContain('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(callbacks.onTableCreated).toHaveBeenCalledTimes(1);
  });
  test("pt-BR validation uses DataTools", () => {
    mockToastError.mockClear();
    const callbacks = props();
    const { baseElement, getByText } = render(<CreateTableModal {...callbacks} />, "pt-BR");
    nameTable(baseElement);
    fireEvent.click(getByText("Adicionar coluna"));
    fireEvent.click(getByText("CREATE TABLE"));
    expect(mockToastError).toHaveBeenCalledWith("Todas as colunas devem ter um nome");
    expect(callbacks.onTableCreated).not.toHaveBeenCalled();
  });
  test("catalogs have equivalent keys and deep English fallback", () => {
    const en = loadMessages("en").DataTools.createTable;
    const pt = loadMessages("pt-BR").DataTools.createTable;
    expect(Object.keys(en).sort()).toEqual(Object.keys(pt).sort());
    const merged = mergeMessages({ createTable: en }, { createTable: { title: pt.title } });
    expect(merged.createTable.title).toBe("Criar tabela");
    expect(merged.createTable.autoIncrement).toBe(en.autoIncrement);
  });
});
