import { Database } from "bun:sqlite";
import { describe, expect, test } from "bun:test";
import {
  AUTO_INCREMENT,
  defaultColumns,
  generateCreateTableSQL,
  reconcileColumns,
  resolveCreateTableDialect,
  type ColumnDefinition,
} from "@/lib/create-table";
import type { DatabaseType } from "@/lib/types";
import { quoteIdentifier } from "@/lib/sql/identifier";

const column = (overrides: Partial<ColumnDefinition> = {}): ColumnDefinition => ({
  name: "value",
  type: "INTEGER",
  isPrimary: false,
  isNullable: true,
  isUnique: false,
  defaultValue: "",
  ...overrides,
});
const generatedKeys: Partial<Record<DatabaseType, string>> = {
  postgres: '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  mysql: "`id` INT AUTO_INCREMENT PRIMARY KEY",
  sqlite: '"id" INTEGER PRIMARY KEY AUTOINCREMENT',
  libsql: '"id" INTEGER PRIMARY KEY AUTOINCREMENT',
  mssql: "[id] INT IDENTITY(1,1) PRIMARY KEY",
  oracle: '"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  duckdb: '"id" INTEGER PRIMARY KEY DEFAULT nextval(\'"widgets_id_seq"\')',
  trino: '"id" INTEGER NOT NULL',
};

describe("Create Table dialect DDL", () => {
  for (const [engine, expected] of Object.entries(generatedKeys)) {
    const dbType = engine as DatabaseType;
    test(`${engine}: upstream generated key and type list`, () => {
      const sql = generateCreateTableSQL("widgets", defaultColumns(dbType), dbType);
      expect(sql).toContain(expected);
      expect(sql).not.toContain("SERIAL");
      expect(sql).not.toContain(AUTO_INCREMENT);
      const dialect = resolveCreateTableDialect(dbType);
      expect(dialect.types).toContain(dialect.keyType);
      expect(dialect.types.includes("JSONB")).toBe(dbType === "postgres");
    });
  }

  for (const dbType of ["postgres", "mysql", "sqlite"] as const) {
    const q = (value: string) => quoteIdentifier(value, dbType);
    test(`${dbType}: basic table, nullable, primary key, unique and literal default`, () => {
      const type = resolveCreateTableDialect(dbType).keyType;
      const sql = generateCreateTableSQL(
        "order",
        [
          column({ name: "key", type, isPrimary: true, isNullable: false }),
          column({ name: "required", type, isNullable: false, isUnique: true, defaultValue: "42" }),
          column({ name: "optional", type }),
          column({ name: "label", type: dbType === "sqlite" ? "TEXT" : "VARCHAR(255)", defaultValue: "'O''Brien'" }),
        ],
        dbType,
      );
      expect(sql).toContain(`CREATE TABLE ${q("order")} (`);
      expect(sql).toContain(`${q("key")} ${type} PRIMARY KEY`);
      expect(sql).toContain(`${q("required")} ${type} NOT NULL UNIQUE DEFAULT 42`);
      expect(sql).toContain(`${q("optional")} ${type},`);
      expect(sql).toContain("DEFAULT 'O''Brien'");
    });
    test(`${dbType}: identifier delimiters cannot inject another statement`, () => {
      const name = 'order"`; DROP TABLE sentinel; --';
      const sql = generateCreateTableSQL(name, [column({ name })], dbType);
      expect(sql).toBe(`CREATE TABLE ${q(name)} (\n  ${q(name)} INTEGER\n);`);
    });
    test(`${dbType}: no auto-increment syntax leaks from another engine`, () => {
      const sql = generateCreateTableSQL("widgets", defaultColumns(dbType), dbType);
      if (dbType !== "postgres") expect(sql).not.toContain("IDENTITY");
      if (dbType !== "mysql") expect(sql).not.toContain("AUTO_INCREMENT");
      if (dbType !== "sqlite") expect(sql).not.toContain("AUTOINCREMENT");
      expect(sql).not.toContain("SERIAL");
    });
  }

  test("SQLite executes the default key and constraints in an isolated in-memory database", () => {
    const db = new Database(":memory:");
    try {
      const sql = generateCreateTableSQL(
        "order",
        [
          ...defaultColumns("sqlite"),
          column({ type: "TEXT", isNullable: false, isUnique: true, defaultValue: "'default_value'" }),
        ],
        "sqlite",
      );
      db.exec(sql);
      db.exec('INSERT INTO "order" DEFAULT VALUES; INSERT INTO "order" ("value") VALUES (\'second\');');
      expect(db.query('SELECT * FROM "order" ORDER BY id').all()).toEqual([
        { id: 1, value: "default_value" },
        { id: 2, value: "second" },
      ]);
      expect(() => db.exec('INSERT INTO "order" ("value") VALUES (NULL)')).toThrow();
      expect(() => db.exec('INSERT INTO "order" ("value") VALUES (\'second\')')).toThrow();
    } finally {
      db.close();
    }
  });

  test("DuckDB quotes its sequence identifier and escapes the nextval string literal", () => {
    const sql = generateCreateTableSQL("o'brien", defaultColumns("duckdb"), "duckdb");
    expect(sql).toStartWith('CREATE SEQUENCE IF NOT EXISTS "o\'brien_id_seq";\n');
    expect(sql).toContain("nextval('\"o''brien_id_seq\"')");
  });
  test("Oracle defaults precede inline constraints", () => {
    expect(generateCreateTableSQL("t", [column({ defaultValue: "42", isNullable: false })], "oracle")).toContain(
      '"value" INTEGER DEFAULT 42 NOT NULL',
    );
  });
  test("Trino does not emit unsupported constraints or generated keys", () => {
    const sql = generateCreateTableSQL(
      "t",
      [column({ isPrimary: true, isUnique: true, isNullable: false, type: AUTO_INCREMENT })],
      "trino",
    );
    expect(sql).toContain('"value" INTEGER NOT NULL');
    expect(sql).not.toMatch(/PRIMARY KEY|UNIQUE|__auto_increment__/);
  });
  test("absent dialect preserves the PostgreSQL fallback", () => {
    expect(generateCreateTableSQL("t", defaultColumns())).toContain("GENERATED BY DEFAULT AS IDENTITY");
  });

  test("dialect switch preserves compatible fields and resets only incompatible options", () => {
    const input = [
      column({ name: "payload", type: "JSONB", defaultValue: "now()" }),
      column({ name: "count", defaultValue: "42", isUnique: true }),
    ];
    const result = reconcileColumns(input, "sqlite");
    expect(result[0]).toEqual({ ...input[0], type: "TEXT", defaultValue: "" });
    expect(result[1]).toEqual(input[1]);
    expect(input[0].type).toBe("JSONB");
    expect(reconcileColumns([column({ type: "INTEGER" })], "mysql")[0].type).toBe("INT");
    expect(reconcileColumns(defaultColumns("postgres"), "trino")[0]).toEqual(defaultColumns("trino")[0]);
    expect(reconcileColumns(defaultColumns("postgres"), "sqlite")[0].type).toBe(AUTO_INCREMENT);
  });
});
